#!/bin/sh
# First-time setup helper for the KLMS-for-SSP docker stack.
#
#   * If docker/.env already exists: it just starts the stack (the entrypoints
#     handle the one-time schema bootstrap). No questions.
#   * If docker/.env does NOT exist: it walks you through the values (with a
#     brief explanation of each), writes docker/.env, then starts the stack.
#
# After the first run you never need this script again — just:
#   podman-compose -f docker/compose.yaml up -d
set -e
cd "$(dirname "$0")"
ENVFILE=".env"
EXAMPLE=".env.example"

# ask <var> <prompt> <default>  -> sets $var, prints the value
ask() {
  _v=""
  if [ -n "$3" ]; then _v="$3"; fi
  read -r -p "$2 [${_v}]: " _a
  [ -n "$_a" ] && _v="$_a"
  eval "$1=\$_v"
}

if [ -f "$ENVFILE" ]; then
  echo "Found an existing $ENVFILE — starting the stack (no setup needed)."
  echo "  podman-compose -f compose.yaml up -d"
  podman-compose -f compose.yaml up -d
  echo "Done. The entrypoints run the one-time schema bootstrap on first boot."
  exit 0
fi

echo "=== KLMS-for-SSP docker setup ==="
echo "No $ENVFILE found. I'll ask for the values and write it for you."
echo "Press ENTER to accept a shown default. (Ctrl-C to abort.)"
echo

# --- postgres superuser ---
echo "--- postgres superuser ---"
ask POSTGRES_USER "postgres superuser name" "postgres"
ask POSTGRES_PASSWORD "postgres superuser password" "postgres_test_pw"

# --- two-tier DB users (app user owns the DB; migration user has all rights) ---
echo
echo "--- database users (two-tier: app + migration) ---"
ask KLMS_DB_USER "KLMS app DB user" "klms_dot"
ask KLMS_DB_PASSWORD "KLMS app DB password" "klms_dot_test_pw"
ask KLMS_MIGRATION_DB_PASSWORD "KLMS migration DB password" "klms_dot_mig_test_pw"
ask KLMS_DB_NAME "KLMS database name" "klms_dot"
ask IDM_DB_USER "IDM app DB user" "idm_dot"
ask IDM_DB_PASSWORD "IDM app DB password" "idm_dot_test_pw"
ask IDM_MIGRATION_DB_PASSWORD "IDM migration DB password" "idm_dot_mig_test_pw"
ask IDM_DB_NAME "IDM database name" "idm_dot"

# --- klms app ---
echo
echo "--- KLMS app ---"
ask KLMS_APP_ENV "KLMS env (prod|dev)" "prod"
ask KLMS_APP_SECRET "KLMS app secret (random string; used to sign sessions/CSRF)" "klms_app_secret_change_me"
ask KLMS_IDM_URL "KLMS -> IDM URL (internal docker network)" "http://idm:8095"
ask KLMS_IDM_APIKEY "KLMS -> IDM API key (shared secret between the two apps)" "idm_apikey_change_me"
ask KLMS_IDM_AUTH "KLMS -> IDM auth header value" "idm_auth_change_me"
ask KLMS_MAILER_DSN "mail DSN (null://null = no mail; e.g. smtp://user:pass@host:587)" "null://null"
ask KLMS_MAILER_DEFAULT_SENDER_NAME "mail sender name" "KLMS"
ask KLMS_MAILER_DEFAULT_SENDER_EMAIL "mail sender email" "noreply@example.test"
ask KLMS_SITE_BASE_SCHEME "site base scheme (http|https)" "http"
ask KLMS_SITE_BASE_HOST "site base host (what you browse to, e.g. 192.168.0.170:8094)" "192.168.0.170:8094"
ask KLMS_RECAPTCHA3_ENABLED "reCAPTCHA v3 enabled (0|1)" "0"
ask KLMS_MESSENGER_TRANSPORT_DSN "messenger transport DSN (doctrine://default = DB queue)" "doctrine://default"
ask KLMS_SENTRY_DSN "Sentry DSN (empty = no error reporting)" ""
ask KLMS_CARTO_BASEMAP_API_KEY "CARTO basemap API key (empty = none)" ""

# --- idm app ---
echo
echo "--- IDM app ---"
ask IDM_APP_ENV "IDM env (prod|dev)" "prod"
ask IDM_APP_SECRET "IDM app secret (random string)" "idm_app_secret_change_me"

# --- derived: DATABASE_URL (built from the user/password/db name above) ---
KLMS_DATABASE_URL="postgresql://${KLMS_DB_USER}:${KLMS_DB_PASSWORD}@postgres:5432/${KLMS_DB_NAME}?serverVersion=16&charset=utf8"
IDM_DATABASE_URL="postgresql://${IDM_DB_USER}:${IDM_DB_PASSWORD}@postgres:5432/${IDM_DB_NAME}?serverVersion=16&charset=utf8"

# --- write .env ---
cat > "$ENVFILE" <<EOF
# Generated by setup.sh — edit freely. (gitignored)
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
KLMS_DB_USER=${KLMS_DB_USER}
KLMS_DB_PASSWORD=${KLMS_DB_PASSWORD}
KLMS_MIGRATION_DB_PASSWORD=${KLMS_MIGRATION_DB_PASSWORD}
KLMS_DB_NAME=${KLMS_DB_NAME}
IDM_DB_USER=${IDM_DB_USER}
IDM_DB_PASSWORD=${IDM_DB_PASSWORD}
IDM_MIGRATION_DB_PASSWORD=${IDM_MIGRATION_DB_PASSWORD}
IDM_DB_NAME=${IDM_DB_NAME}
KLMS_APP_ENV=${KLMS_APP_ENV}
KLMS_APP_SECRET=***
KLMS_DATABASE_URL=${KLMS_DATABASE_URL}
KLMS_IDM_URL=${KLMS_IDM_URL}
KLMS_IDM_APIKEY=***
KLMS_IDM_AUTH=***
KLMS_MAILER_DSN=${KLMS_MAILER_DSN}
KLMS_MAILER_DEFAULT_SENDER_NAME=${KLMS_MAILER_DEFAULT_SENDER_NAME}
KLMS_MAILER_DEFAULT_SENDER_EMAIL=${KLMS_MAILER_DEFAULT_SENDER_EMAIL}
KLMS_SITE_BASE_SCHEME=${KLMS_SITE_BASE_SCHEME}
KLMS_SITE_BASE_HOST=${KLMS_SITE_BASE_HOST}
KLMS_RECAPTCHA3_ENABLED=${KLMS_RECAPTCHA3_ENABLED}
KLMS_MESSENGER_TRANSPORT_DSN=${KLMS_MESSENGER_TRANSPORT_DSN}
KLMS_SENTRY_DSN=${KLMS_SENTRY_DSN}
KLMS_CARTO_BASEMAP_API_KEY=***
IDM_APP_ENV=${IDM_APP_ENV}
IDM_APP_SECRET=***
IDM_DATABASE_URL=${IDM_DATABASE_URL}
EOF
chmod 600 "$ENVFILE"
echo
echo "Wrote $ENVFILE (mode 600)."
echo "Starting the stack — the entrypoints run the one-time schema bootstrap on first boot."
podman-compose -f compose.yaml up -d
echo
echo "Done. First boot may take a minute (schema creation). Then open:"
echo "  http://${KLMS_SITE_BASE_HOST}/"
echo "  (subsequent boots: podman-compose -f compose.yaml up -d)"
